[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.2"
bevy_mod_debugdump = "0.11.1"
bevying = { path = ".." }
kanal = "0.1.0-pre8"
tracing = "0.1.40"
tracing-appender = "0.2.3"
tracing-subscriber = "0.3.18"
